#:kivy 2.1.0
Root:

<Root>
    BoxLayout:
        orientation:'vertical'

        Button:
            id:button1
            text:'+1'
            on_release:label1.value += 1
        
        Button:
            id:button2
            text:'Reset'
            on_release:label1.value = 0
        
        Label:
            id:label1
            value:0
            text:str(self.value)

            

        



